### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by VitorDiass**
Added website and Slack link to the README.md

### CODE REVIEW

**Comment by SunyataZero** [comment]
We also need to update the readme for the services project here on github, but to avoid duplication of information maybe it's better to collect all documentation in one place? What do you think @Code4SocialGood ?

**Comment by VitorDiass** [comment]
I've also added the same information to the README.md in services

**Comment by SunyataZero** [comment]
@VitorDiass Okay but i cannot see that change, what am i missing? https://github.com/Code4SocialGood/c4sg-services

**Comment by VitorDiass** [comment]
@SunyataZero I realised i did the same PR twice, already closed one of them. 
I dont know why you cant see that change.

**Comment by SunyataZero** [comment]
I think someone with push access to the repo also need to "merge" the change, in any case i'm merging this change and thank you for your help. I'll talk with @Code4SocialGood (Jenny) about the other readme file. Kind Regards, Tord

**Comment by VitorDiass** [comment]
Thanks! 
Notice me if something is missing or broken
Greetings, VitorDiass

**Pull request merged**
