### PR TITLE
Issue1363

### PR DESCRIPTION
**Pull request by bealearnscode**
I added a FAB to the cards on the homepage. Not sure if I was supposed to work on interactivity and positioning

### CODE REVIEW

**Comment by Code4SocialGood** [comment]
@bealearnscode This app use indent of 2 spaces instead of 4 spaces. Could you make the code change only for addressing the issue of #1363, and don't change the coding format? Otherwise it is hard for code review.

**Comment by bealearnscode** [comment]
I believe I fixed the indentation. My code editor defaults to four tabs.

**Comment by Code4SocialGood** [comment]
@bealearnscode Could you please upload a screen shot of what the UI looks like after the code change?

**Comment by bealearnscode** [comment]
cfsg-web

**Comment by Code4SocialGood** [comment]
@bealearnscode Thanks for the screen shot.

**Comment by Code4SocialGood** [comment]
@bealearnscode We consulted the UI designer and it is suggested the current look and feel is better since it is standard representation on UI. So we will close this PR and the corresponding issue.

**Pull request closed without merging**
