### PR TITLE
Major footer's style changes

### PR DESCRIPTION
**Pull request by justindiaw**

### CODE REVIEW

**Comment by russon77** [comment]
@justindiaw could you post pictures of the updates?

**Comment by justindiaw** [comment]
@russon77 
cut

**Comment by justindiaw** [comment]
@russon77 
And also I got a question for you. I noticed that you added login authentication to the website. To see the full version of the page, which is the one after you have logged in, what should I do?

**Comment by russon77** [comment]
@justindiaw i did not add that! @Code4SocialGood do we have the login info posted somewhere?

**Comment by Code4SocialGood** [comment]
@russon77 @justindiaw test accounts are posted to the Slack announcement channel

**Pull request merged**
