### PR TITLE
Project Detail Page - Right Panel - Populate Opportunities from Nonprofit #152

### PR DESCRIPTION
**Pull request by joshisayali**
Kindly review and let me know in case of any changes.

### CODE REVIEW

**Comment by russon77** [comment]
@joshisayali please merge the latest master code into your PR branch - i suspect that tslint will have some complaints!

**Comment by joshisayali** [comment]
Okay.

**Comment by joshisayali** [comment]
Submitted another pull request #215

**Comment by Code4SocialGood** [comment]
Replaced with #215.

**Pull request closed without merging**
