### PR TITLE
Add file via upload

### PR DESCRIPTION
**Pull request by chetoos**
My Settings - Summary Textarea #572 completed, changed summary text area to 1 line

### CODE REVIEW

**Comment by Code4SocialGood** [comment]
No UI difference can be seen from this PR. Could you post a screen shot from your local running app?

image

**Comment by chetoos** [comment]
image
Admittedly I don't have a locally running server yet, not sure why it's not, but this is what it looks like when I open the HTML file.

**Comment by Code4SocialGood** [comment]
Please setup local server and test the page within the app.

**Comment by chetoos** [comment]
I have set up my local server, I just don't know how to navigate within it. When I run it, it runs the index page, which is blank

**Comment by Code4SocialGood** [comment]
Your setup in incorrect. If it is correct, it should look like the dev server: http://dev.code4socialgood.org/

**Comment by chetoos** [comment]
I will get around to this later, once I've set up my local server properly. I have it set to the wrong html file right now, and I need to figure out how to redirect it to the proper one.

**Comment by chetoos** [comment]
I could use some help figuring out my apache server. I downloaded apache and configured it to run the home page, but it only loaded the shell of the HTML file in there, without any of the other stuff, and I want to help better.

**Comment by Code4SocialGood** [comment]
Issue is resolved and closed.

**Pull request closed without merging**
