### PR TITLE
Changed the color of Menu Item in Mobile device.

### PR DESCRIPTION
**Pull request by sabrinadowla14**
I have changed the color of Menu item to black on the Mobile device.

Thanks,
Sabrina

### CODE REVIEW

**Comment by Code4SocialGood** [comment]
@sabrinadowla14 Which Github issue is this PR for?

**Comment by sabrinadowla14** [comment]
Hi,

It's for:
Home Page - Menu Item - Color #1624

Thanks,

Sabrina

**Comment by Code4SocialGood** [comment]
@sabrinadowla14 Please resolve conflict on this PR

**Comment by Code4SocialGood** [comment]
Code conflict not resolved. Close this PR.

**Pull request closed without merging**
