### PR TITLE
Alignleft

### PR DESCRIPTION
**Pull request by sahithyakatta**
Organization List & Volunteer List Page - Left Align · Issue #642 · Code4SocialGood/c4sg-web

Left align the second line in the card.

### CODE REVIEW

**Comment by Code4SocialGood** [comment]
1. Please resolve the build error.
2. Please post a screen shot here of how the web page look like locally.

**Comment by Code4SocialGood** [comment]
Issue is resolved and closed.

**Comment by sahithyakatta** [comment]
screenshot

**Comment by sahithyakatta** [comment]
screenshot

**Comment by Code4SocialGood** [comment]
No need for the PR, issue resolved.

**Pull request closed without merging**
