### PR TITLE
completed issue 1426

### PR DESCRIPTION
**Pull request by jhonemillan**
Completed 1426

### CODE REVIEW

**Comment by Code4SocialGood** [comment]
@jhonemillan 
1. Please upload a screen shot of how the page looks like in local dev environment
2. Please remove the Back to Search Result button on the green title bar
image

**Comment by jhonemillan** [comment]
project

**Comment by jhonemillan** [comment]
I have made another change, i deleted button on header as you requested.
Can you confirm, you can see it?

**Comment by Code4SocialGood** [comment]
@jhonemillan 

1. Yes, the button on green bar is removed, thanks

2. Please make the button you added as grey background. Please see wireframe below.
image

**Comment by jhonemillan** [comment]
Please, check it again.

**Pull request merged**
