### PR TITLE
Main changes to opportunity list styling

### PR DESCRIPTION
**Pull request by justindiaw**
Remove most of borders
Card design for the list
Fix the bug of header having no color
Fix the bug of header having border in home page

PS: Not a perfect version, but we can discuss about those main changes.

### CODE REVIEW

**Comment by justindiaw** [comment]
image

**Comment by justindiaw** [comment]
image

**Comment by justindiaw** [comment]
In addition, for my suggestion, we should use high quality images for the avatar. Colorfull avatar pics will suit this style well.

**Comment by Code4SocialGood** [comment]
BTW, here is the piece of wireframe I have. @wilber, can you post here the mock up screen also.
image

**Comment by Code4SocialGood** [comment]
Terms have been mentioned about such as sacc, scss, jade, bootstrap, materialize, grid, .... This is a good opportunity for us to discuss the technology choices and make our (tentative) direction by reviewing this PR.

**Comment by justindiaw** [comment]
@KlausMana Actually, I did as what you say. I edit the scss file on my own and removed some materialize settings. I modify this based on the last coder's version. That's why you see some trace of Materialize but the not so important ones in the codes. In this version I tried to move away from it. But, anyway, I would agree not to use Materialize.

**Comment by justindiaw** [comment]
@Code4SocialGood The experience working with Materialize is not quite pleasant for me.

**Comment by justindiaw** [comment]
@Code4SocialGood Let me shrink the avatar size, wait

**Comment by Code4SocialGood** [comment]
@justindiaw The discussion thread has been hanging for a long time about what to use in this app, materialize or bootstrap or....hopefully we can make a choice together now, with the experience we gained over the past months

**Comment by justindiaw** [comment]
hold on guys, I will do changes to the avatar. I will pull again this afternoon.

**Comment by data-perception** [comment]
@justindiaw . Glad to see more changes in frontend. However, I think we are spending and/or wasting too much time without an agreement for design.
Currently, we have reached partially to an agreement with the design, some files are in #UI/UX channel in Slack.
It would be awesome your suggestions and editions in those designs, in order to follow only one style and avoid making more designs.

**Comment by hdwilber** [comment]
@justindiaw . Glad to see more changes in frontend. However, I think we are spending and/or wasting too much time without an agreement for design.
Currently, we have reached partially to an agreement with the design, some files are in #UI/UX channel in Slack.
It would be awesome your suggestions and editions in those designs, in order to follow only one style and avoid making more designs.

**Comment by Code4SocialGood** [comment]
@hdwilber Are you able to deliver a PR as prototype for the design you proposed? Either on the same page (Project List) or a different page (like User List)?

**Comment by hdwilber** [comment]
User List page
Project List page

**Comment by Code4SocialGood** [comment]
Could we get a list of topics and discuss one by one? 
1. Materialize: we agreed no materialize, and justin's code doesn't use materialize. Are we good on this topic?
2. What's next?

**Pull request merged**
